package com.example.springcloudconsumerdeptfeign;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;
import org.springframework.cloud.netflix.hystrix.EnableHystrix;
import org.springframework.cloud.openfeign.EnableFeignClients;
import org.springframework.context.annotation.ComponentScan;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication(scanBasePackages = {"service", "com.example.springcloudconsumerdeptfeign"})
@EnableEurekaClient
@EnableFeignClients(basePackages = "service")
@EnableHystrix
public class SpringCloudConsumerDeptFeignApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringCloudConsumerDeptFeignApplication.class, args);
    }

}
