package com.example.springcloudconsumerdept80;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableEurekaClient
public class SpringCloudConsumerDept80Application {
    public static void main(String[] args) {
        SpringApplication.run(SpringCloudConsumerDept80Application.class, args);
    }
}
