server:
  port: 8081

# EUREKA的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/,http://localhost:7004/eureka/
    register-with-eureka: false # 不向Eureka注册自己

# Spring Cloud 提供了重试机制，直接在配置文件进行配置即可，但如果加了重试，请务必保证有更新操作接口的幂等性
spring:
  application:
    name: consumer

# 开启服务降级
feign:
  circuitbreaker:
    enabled: true


